pipeline {
    agent any
    options {
        skipDefaultCheckout(true)
    }

    stages {

        stage('Init environment') {
            steps {
                cleanWs()
                checkout scm
            }
        }

        // stage('Code QA') {
        //     steps {
        //         //sh'''
        //         //git config --global --add safe.directory $(pwd)
        //         //git init .
        //         //'''
        //         echo 'Setting up virtual env'
        //         sh'''
        //         #chown -R 1000 $(pwd)
        //         python3 -m venv venv
        //         . venv/bin/activate
        //         git config --unset-all core.hooksPath
        //         pip install --upgrade pip && pip install pre-commit
        //         pre-commit install
        //         pre-commit run --files src/projects/mic/**/* --show-diff-on-failure
        //         # pre-commit run --from-ref origin/HEAD --to-ref HEAD
        //         '''
        //     }
        // }
        stage('Cloning dependencies') {
            steps {
                echo 'cloning odoo-common 16'
                withCredentials([gitUsernamePassword(credentialsId: 'jenkins-upa-test', gitToolName: 'git-tool')]) {
                    sh 'git clone --branch=16.0 --depth=1 https://github.com/microcom/odoo-common.git'
                }
                sh 'mv ./odoo-common ./src/projects/'
                echo 'clone oca/project'
                sh 'git clone --branch=16.0 --depth=1 https://github.com/OCA/project.git'
                sh 'mv ./project ./src/projects/'
                sh 'ls -l ./src/projects/.'
            }
        }

        stage('Uni Tests') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'my-docker-reg-upa', usernameVariable: 'docker-uname', passwordVariable: 'docker-pwd')]) {
                    echo 'build image'
                    sh '''
                    docker login -u $docker-uname -p $docker-pwd
                    docker build -t my-pgi-16.0:${env.BUILD_ID} .
                    '''
                    echo 'run tests'
                }
            }

        }

    }
}